import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import favicon from './images/favicon.png'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mambow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">

      <body className={inter.className}>{children}</body>
    </html>
  );
}
